spring:
  application:
    name: product-service
  config:
    import: "configserver:"

firestore:
  project-id: ${FIRESTORE_PROJECT_ID:kaveesha-cloud}
  products-collection: ${FIRESTORE_PRODUCTS_COLLECTION:products}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloud:
  config:
    uri: http://config.platform:8888
